[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fastrdp"
version = "0.0.1"
description = "Implementation of the Ramer-Douglas-Peucker algorithm"
readme = "README.md"
authors = [{ name = "Robert Dahl Jacobsen" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy >= 1.26.0",
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = ["build", "pytest", "wheel"]
docs = ["matplotlib", "rdp"]

[project.urls]
Homepage = "https://github.com/robertdj/fastrdp"
