name: Test Python

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment
        env:
          BIN: ${{ matrix.os == 'windows-latest' && 'Scripts' || 'bin' }}
        run: |
          python -m venv .venv
          echo "$GITHUB_WORKSPACE/.venv/$BIN" >> $GITHUB_PATH

      - name: Install RDP & dependencies
        run: |
          python setup.py build
          pip install '.[dev]'

      - name: Run tests
        run: pytest


  readme:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtual environment
      run: |
        python -m venv .venv
        echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

    - name: Install RDP & dependencies
      run: |
        python setup.py build
        pip install '.[docs]'

    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2
      with:
        path: README.qmd